package-lock.json, package.json, src/App.js, src/redux/store/index.js
=> Group 8 redux estrutura

package-lock.json, public/Notes.jsx, src/App.js, src/App.test.js, src/hooks/usePersistedState.js, src/hooks/useRecipe.js, src/pages/Foods.jsx, src/pages/Login.jsx, src/routes/Routes.jsx, src/store/RecipeContext.jsx
=> [Grupo 15] - Req 2-8

src/App.js, src/pages/Login/index.js
=> Feat: Login Screen

package-lock.json, package.json, src/App.css, src/App.js, src/compenents/Footer.js, src/compenents/Footers.js, src/styles/Footer.css
=> [Group 14] Feat: Req-19

src/App.js, src/pages/Explore.jsx, src/pages/Profile.jsx, src/styles/profile.js
=> [ Grupo 16] - Tela de Perfil

src/App.js, src/context/UserProvider.js, src/pages/Login.js, src/pages/Main.js, src/tests/App.test.js, src/tests/Login.test.js
feat: Login Page, fix: fixed overall structure of providers due to lint error issues, added Browser Router
=> Login Page:

src/components/LowerMenu.js
Já deixei o componente LowerMenu pronto. Basta chamá-lo dentro do componente MainRecipes que vai funcionar no avaliador e o requisito 19 vai passar. O MainRecipes vai ser criado futuramente.
=> Requisito 19

package-lock.json, package.json, src/components/LowerMenu.js
Esse requisito deve ser mergeado somente após o merge do requisito 19.
=> Requisito 20

src/App.js, src/components/footer.jsx, src/pages/Drinks.jsx, src/pages/Explorer.jsx, src/pages/Perfil.jsx, src/pages/RecipesDone.jsx, src/pages/RecipesFav.jsx
Criação de 16 rotas e as páginas principais de cada rota
=> [Group 24] Routes and Principal pages created

cypress/integration/login_spec.js, src/App.js, src/App.test.js, src/pages/Login.jsx, src/pages/Recipes.jsx
=> [Group 7]  page login

src/App.js, src/components/BottomMenu.jsx, src/components/Routes.js, src/contexts/RecipesContext.jsx, src/contexts/RecipesProvider.jsx, src/contexts/UserContext.jsx, src/contexts/UserProvider.jsx, src/pages/DrinksRecipes.jsx, src/pages/ExploreDrinksIngredients.jsx, src/pages/ExploreDrinksRecipes.jsx, src/pages/ExploreFoodsIngredients.jsx, src/pages/ExploreFoodsRecipes.jsx, src/pages/ExploreOriginLocal.jsx, src/pages/ExploreRecipes.jsx, src/pages/FoodRecipes.jsx, src/pages/Login.jsx, src/pages/Perfil.jsx, src/styles/BottomMenu.css, src/tests/BottomMenu.test.js, src/tests/renderWithRouter.js
=> Main-Group-22- req-19a24

cypress/integration/login_spec.js, src/context/UserContext.jsx, src/pages/Login.jsx
=> [Grupo 16] - Página de Login

src/Routes.js, src/components/Header.jsx, src/components/HeaderSearchbar.jsx, src/components/HeaderWithSearch.jsx, src/context/Provider.js, src/pages/BeveragePage/Beverage.js, src/pages/ExplorePage/ExplBeverageIng.js, src/pages/ExplorePage/ExplFoodIng.js, src/pages/ExplorePage/Explore.js, src/pages/ExplorePage/ExploreBeverage.js, src/pages/ExplorePage/ExploreFood.js, src/pages/ExplorePage/ExploreFoodArea.js, src/pages/ProfileScreen/ProfileScreen.jsx, src/pages/RecipesDone/RecipesDone.js, src/pages/RecipesFav/RecipesFav.jsx
Created Routes, dynamic routes created only to pass on tests, must be implemented on specific requirement. Implementation without style
=> [Main group 12] req9

src/App.js, src/components/LowerMenu.js, src/configs/configs.js, src/contexts/app/AppContext.js, src/contexts/app/AppProvider.js, src/contexts/drinks/DrinksProvider.js, src/index.js
Correctly redirects to the cocktail page
=> :sparkles: Requisito 22

src/components/LowerMenu.js
=> :sparkles: Requisito 23

src/components/Header/Header.js, src/components/Header/SearchBar.js, src/components/Header/index.js, src/pages/Bebidas.js, src/pages/Comidas.js, src/pages/Explorar.js, src/pages/ExplorarBebidas.js, src/pages/ExplorarBebidasIng.js, src/pages/ExplorarComidas.js, src/pages/ExplorarComidasArea.js, src/pages/ExplorarComidasIng.js, src/pages/Perfil.js, src/pages/ReceitasFavoritas.js, src/pages/ReceitasFeitas.js
Fala grupo, acabei fazendo os requisitos do 9 ao 13 nessa branch, pois faziam parte do mesmo componente.
=> Main group 23 Requisitos 9 ao 13

src/App.test.js, src/App.test.js.txt, src/pages/LoginPage/Login.js, src/pages/ProfileScreen/ProfileScreen.jsx, src/pages/RecipesFav/RecipesFav.jsx, src/tests/ProfileScreen.test.js
Implementei os testes da página ProfileScreen.
Quando as páginas FavRecipes e DoneRecipes forem concluídas estes testes devem ser reajustados!
=> [ Group 12 ] Tests requirements 82 - 87

src/actions/index.js, src/components/SearchButton.jsx
Reverts tryber/sd-010-a-project-recipes-app#327
=> Revert "Feat: requisitos 13 e 14 "

src/Components/Auth.jsx, src/__mocks__/localStorage.js, src/__mocks__/rawData.js, src/__tests__/Login.spec.js, src/__tests_helpers__/renderWithRouter.js, src/__tests_helpers__/renderWithRouterAndRedux.js, src/index.js, src/pages/Login.jsx, src/services/localStorage.js, src/slices/auth.js, src/slices/cocktailsToken.js, src/slices/mealsToken.js, src/slices/rootReducer.js, src/slices/user.js
=> Group 32 - Login

src/App.js, src/Components/Header.jsx, src/Components/MainContainer.jsx, src/hooks/useMenuType.js, src/hooks/useSetTitleWithRouteName.js, src/index.css, src/pages/Application/MenuList.js, src/pages/Application/index.js
Foram adicionados os arquivos e implementadas as funções reponsáveis pelo roteamento da aplicação.
=> Group - 32 Route structure

src/Pages/MainRecipes.js, src/components/SearchBar.js
Req.13 - adicionar input , radio buttons e button a Search Bar
=> Feat: Req13 - adiciona input e radio buttons na searchbar

src/App.test.js, src/components/Header.js, src/styles/Header.css
=> [ Main group 3 ] Criação de testes e estilização do componente Header 

src/Pages/ExploreDrinks.js
=> fix: rota requisito 72

package.json, src/pages/ExplorarBebidasIngredientes.js
=> [Grupo 4] resolvendo problema no merge

src/components/Main/CategoryButtons.js, src/components/Main/RecipeCard.js, src/contexts/FoodProvider.js, src/pages/Comidas.js, src/services/cocktailAPI.js, src/services/mealAPI.js
=> Main group 23 req28

src/App.test.js, src/actions/index.js, src/components/ExploreButton.jsx, src/pages/ExpBebidas.jsx, src/pages/ExpComidas.jsx, src/pages/ExpComidasIng.jsx, src/reducers/index.js, src/reducers/recipe.js
Req 74 - estrutura parcial - falta paginação dinâmica
=> [ Explorar Page] - Reqs 70, 71, 72, 73

src/pages/DrinkInProgress/index.js, src/pages/ExplorePage/index.js, src/pages/FoodDetails/index.js, src/pages/FoodInProgress/index.js, src/pages/ProfilePage/index.js, src/services/Routes.js
=> Main group 27 - Explore Screen

src/App.css, src/components/CardList/CardList.jsx, src/components/Carousel/Carousel.jsx, src/components/Carousel/CarouselCard.jsx, src/components/Carousel/styles.js, src/components/MealVideo/MealVideo.jsx, src/components/RecipeInfo/RecipeInfo.jsx, src/components/RecipeIngredients/RecipeIngredients.jsx, src/helpers/carouselData.js, src/pages/RecipeDetails.jsx, src/services/fetchFilteredRecipes.js, src/services/formatingService.js, src/styles/recipeDetails.js
=> [Grupo 16] - Tela de detalhes da receita - em andamento

src/pages/DetailsPages/ComponentAuxProgress.js, src/pages/DetailsPages/components/IngredinetsRadio.jsx, src/pages/DetailsPages/components/buttons/ButtonDoneRecipe.jsx, src/pages/DetailsPages/components/buttons/ButtonMakeRecipeFood.jsx, src/pages/DetailsPages/components/buttons/ButtonShare.jsx, src/pages/DetailsPages/components/index.js, src/pages/DetailsPages/components/styles/styleIngredientsCheck.css, src/pages/DetailsPages/components/styles/styleRecommends.css, src/pages/recipes-main/index.css, src/services/localStorage/doneRecipes.js, src/services/localStorage/setIdAndIngredients.js, src/services/localStorage/setProgressRecipesLS.js
Requisitos do 47 ao 53 passando.
Como a checlist de ingredientes ta funcionando? MÁGICA!
=> [Group 12] Reqs 47-53 :mage_man:

src/context/Provider.js, src/pages/RecipesDone/Recipes.js, src/pages/RecipesDone/RecipesDone.js
Recupera as informações de receitas concluídas do localStorage
=> [Group 12 ] Fix - Retrive information from localStorag

src/App.js, src/Components/DrinksList.jsx, src/Components/MainScreen.jsx, src/Components/MealsList.jsx, src/Components/MenuCard.jsx, src/__mocks__/mealsData.js, src/__tests__/Explore.spec.js, src/pages/Application/Explore/ExploreArea.js, src/services/apisMaps.js, src/services/drinksAPI.js, src/services/mealAPI.js
=> Group 32 - Explore Area Screen

src/components/Header.jsx, src/components/SearchBar.jsx, src/context/RecipeProvider.js, src/pages/DrinkPage/index.js, src/pages/FoodPage/index.js, src/services/apiRequests.js
Quase pronto ainda falta o alerta caso nenhum resultado for encontrado
=> [Group 27] Search bar Fix

src/components/DetailsHeader.js, src/components/FavoriteButton.js, src/components/ShareButton.js
Apenas para separar o botao de like e o botao de compartilhar em novos componentes
=> Main group 23 split components

src/pages/FinishedRecipies.jsx
=> :sparkles: DoneRecipes Screen

src/components/ButtonsProfile.jsx, src/components/Header.jsx, src/pages/Profile.jsx, src/tests/Header.test.js, src/tests/Profile.test.js
Tela de perfil, requisitos e teste de cobertura.
=> [Group 7 ] Tela de perfil - req e testes

src/components/Main/CategoryButtons.js, src/components/Main/RecipeCard.js
25 a 31 passando no teste
32 pronto (redireciona para tela de detalhes dos cards) mas não passa no teste ainda (estou no plantão pra saber o porquê, talvez  porquê não tem nenhum card ainda na tela de detalhes)
=> Main group 23 req30

src/compenents/SearchBarHeader.js, src/contexts/RecipesAppContext.js, src/pages/Perfil.js, src/pages/Profile.js, src/styles/Profile.css
Resolvendo conflitos de merges
=> [Grupo 14] merge profile

src/Components/Footer.jsx, src/__tests__/Footer.spec.js, src/pages/Application/index.js
=> Group 32 - Footer

src/pages/ProfileScreen/ProfileScreen.jsx
Reverts tryber/sd-010-a-project-recipes-app#720
=> Revert "[Group 12] fix logout button"

src/Components/MainScreen.jsx, src/pages/Application/index.js, src/services/apisMaps.js
=> [Grupo 32] - Tela Principal 

src/components/FavoriteRecipeCard.jsx, src/context/RecipeProvider.js, src/pages/DoneRecipes/index.js, src/pages/FavoriteRecipes/index.js
=> [Group 27] -> feat: favorite recipes screen

src/pages/Perfil.js
Requisitos 82 a 87 Concluídos, Testados e Aprovados
=> Main group 23 req82

src/components/FavoriteButton.js, src/components/ReceitasFavoritas/FavoriteRecipeCard.js, src/components/ReceitasFavoritas/UnfavoriteButton.js, src/contexts/FavoritesProvider.js, src/pages/ReceitasFavoritas.js, src/style/FavoriteRecipeCard.css
=> [Main group 23] Página de receitas Favoritas

package-lock.json, src/App.js, src/pages/Explorer.jsx
=> jesus-requisitos676869

src/context/Provider.js, src/pages/DetailsPages/components/buttons/ButtonMakeRecipeDrink.jsx, src/pages/DetailsPages/components/buttons/ButtonMakeRecipeFood.jsx, src/tests/ProfileScreen.test.js
Criei uma função nos botões que iniciam as receitas.
O provider já tinha as funções que iniciavam o localStorage (inProgressRecipes). Passei essas funções no Context.
Fiz um useEffect que verifica se existe o campo inProgressRecipe, se não existir ele iniciar o localStorage.
=> [Group 12] Correcao do problema de limpar o localStorage

src/App.js, src/pages/ExplorarComidasArea.js, src/pages/NotFound.js, src/services/mealAPI.js
Desafios 78, 79, 80 e 81 concluídos :)
=> Main group 23 req78

src/components/Header/components/Search/index.jsx, src/components/Header/components/Search/styles.module.scss, src/components/Header/index.jsx, src/components/Header/styles.module.scss, src/context/Recipes.jsx, src/pages/MainRecipes/components/Categories/index.jsx, src/services/drinksData.js, src/services/mealsData.js, src/services/recipesData.js
=> [GRUPO 21] (Receitas/Global) Componente de busca que permite encontrar receitas

src/pages/RecipesDone/Recipes.js, src/pages/RecipesDone/index.css, src/pages/RecipesFav/Recipes.js, src/pages/RecipesFav/index.css, src/pages/recipes-main/index.css
Estilização final da pagina de receitas feitas e favoritas
=> Group 12 css maria favorite recipes

src/Components/FavoriteRecipeButton.jsx, src/Components/FavoriteRecipeCard.jsx, src/pages/Application/Menu/RecipeDetails/Header.js
fix a bug where the favorite icon didn't display the corresponding test id
=> Group 32 - Favorite Recipe

src/components/footer/index.jsx, src/components/footer/styles.module.scss, src/pages/Explore/index.jsx, src/pages/MainRecipes/index.jsx, src/pages/Perfil/index.jsx
=> [GRUPO 21] (Footer) Menu inferior

src/components/RecomendationCards.jsx
I put the link tag below the image
=> Fix - img width in carrousel.

src/App.js, src/components/Header/index.jsx, src/components/Header/styles.module.scss, src/components/RecipesCardsGrid/components/RecipeSimpleCard/index.jsx, src/components/RecipesCardsGrid/index.jsx, src/components/footer/index.jsx, src/components/footer/styles.module.scss, src/context/Recipes.jsx, src/global.scss, src/pages/Explore/index.jsx, src/pages/MainRecipes/styles.module.scss, src/pages/Perfil/index.jsx, src/pages/Perfil/styles.module.scss, src/pages/Recipe/components/Ingredient/index.jsx, src/pages/Recipe/components/Ingredient/styles.module.scss, src/pages/Recipe/components/Recommendations/index.jsx, src/pages/Recipe/components/Recommendations/styles.module.scss, src/pages/Recipe/components/StartOrFinishRecipeBtn/index.jsx, src/pages/Recipe/components/StartOrFinishRecipeBtn/styles.module.scss, src/pages/Recipe/components/Video/index.jsx, src/pages/Recipe/index.jsx, src/pages/Recipe/styles.module.scss, src/services/recipesData.js
=> [GRUPO 21] (Receita) Renderiza os detalhes da receita

src/App.js, src/components/Header/components/Search/index.jsx, src/components/Header/index.jsx, src/components/RecipesCardsGrid/components/RecipeSimpleCard/index.jsx, src/components/RecipesCardsGrid/index.jsx, src/context/Recipes.jsx, src/pages/Explore/components/Dropdown/index.jsx, src/pages/Explore/components/ExploreCards/index.jsx, src/pages/Explore/components/ExploreCards/styles.module.scss, src/pages/Explore/index.jsx, src/pages/Explore/styles.module.scss, src/pages/MainRecipes/index.jsx, src/pages/Recipe/components/Recommendations/index.jsx, src/pages/Recipe/components/Video/index.jsx, src/services/drinksData.js, src/services/mealsData.js
=> [GRUPO 21] (Explorar origem) Renderiza todas as receitas e filtra por origem.

src/context/AppContext.jsx, src/pages/RecipeDetails/Ingredients.js, src/pages/RecipeDetails/StartRecipeBtn.js, src/pages/RecipeDetails/index.js
Requirement 40 not passing yet
=> [ Group 31 ] details page continuation

src/App.js, src/components/HorizontalRecipeCard/index.jsx, src/components/HorizontalRecipeCard/styles.module.scss, src/pages/DoneRecipes/index.jsx, src/pages/DoneRecipes/styles.module.scss, src/pages/Explore/index.jsx
=> [GRUPO 21] (Receitas Feitas) Renderiza todos os cards de todas as receitas feitas

src/components/RecipeCardDetailDrink.jsx, src/components/RecipeCardDetailFood.jsx, src/components/componentsDetails/BtnInitiateRecipe.jsx
=> [Group 27] Remaining Requirements

src/App.js, src/components/HorizontalFavoriteRecipeCard/index.jsx, src/components/HorizontalFavoriteRecipeCard/styles.module.scss, src/context/Recipes.jsx, src/pages/FavoriteRecipes/index.jsx, src/pages/FavoriteRecipes/styles.module.scss
Criação da tela de receitas favoritas
=> [Grupo 21] (Receitas Favoritas) 

src/components/Recipe/FavoriteDrink.js, src/components/Recipe/FavoriteMeal.js, src/pages/BebidasEmProcesso.js, src/pages/ComidasEmProcesso.js
Arrumando um pequeno bug relacionado a salvar as receitas feitas
=> [Grupo 4] hotfix das receitas concluídas
